### ISSUE TITLE
Create a new text file in the contributors

### ISSUE THREAD

**Issue by chanmol1999** [NJACKWinterOfCode/Get-Started#3]
Create a new text file in the contributors folder with your github handle as the file name. This file should contain your name. A sample file has been provided.

**Comment by saumya1singh** [comment]
@chanmol1999   Review my P.R here #25  and merge .

**Comment by vkgupta857** [comment]
I have made a pull request #33 . Validate and merge it.

**Comment by sonali2105** [comment]
I have made a pull request #72 .Validate my P.R and merge it.

**Comment by sonali2105** [comment]
I have a made request #74 .Validate this and merge it.

**Comment by mansiagarwal451** [comment]
I have made a pull request #76. Please review and merge.

**Comment by hashtagaps** [comment]
please review my PR and kindly merge . #103

**Comment by Shashank07-creator** [comment]
please review my PR and merge. #113

**Comment by vanshita25** [comment]
please review my PR and merge #117

**Comment by ivaibhavjindal** [comment]
Please review and merge #131

**Comment by snehaM2210** [comment]
Please preview and merge #137

**Comment by akshitagupta15june** [comment]
PLease review #138
